### ISSUE TITLE
fedora-x64-20231201

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#386] opened 2024-02-19 21:49 UTC
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/vathpela/shim-review/tree/fedora-x64-20231201

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
$ sha256sum shimx64.efi
d7ddb10719785f2660b87f84f8603987db145816f1a98b277145ed4a7828f086  shimx64.efi
$ pesign -h -P -i shimx64.efi
271403343af4a4dfb5fcc83faa83ba3ebde5c3bc76fc6ab1a14f7d5ce0ac1242 shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/241 (for shim-15.6)

**Comment by SherifNagy** [comment] 2024-02-20 17:48
I think SHIM's sbat values has a mistake in this entry shim.rh,3,The Fedora Project,shim,15.6,https://src.fedoraproject.org/rpms/shim-unsigned-x64

**Comment by vathpela** [comment] 2024-02-20 18:27
Should be fixed.  New hashes:
```
$ sha256sum shimx64.efi
8dfa5fee2087612955889b3546d15d64d04ef54edd4465cb15ffadea816920ef  shimx64.efi
$ pesign -h -P -i shimx64.efi
94896c17d49fc8c8df0cc2836611586edab1615ce7cb58cf13fc5798de56b367 shimx64.efi
```

**Comment by SherifNagy** [comment] 2024-02-20 22:37
While I am not an official reviewer, here are my comments "looking at latest tag: https://github.com/vathpela/shim-review/tree/fedora-x64-20231201":

* SHIM reproduce okay with the provided dockerfile and the hashes matches
* SHIM sources within the SRPM matches the release hash
* SHIM's CA is self signed, valid for almost 13 years and 2048 bits
* SHIM's SBAT entry for the vendor looks good, got bumped to 3 from 2 and two extra entries has been added:
   * shim.redhat,3,The Fedora Project,shim,15.8,https://src.fedoraproject.org/rpms/shim-unsigned-x64
   * shim.fedora,3,The Fedora Project,shim,15.8,https://src.fedoraproject.org/rpms/shim-unsigned-x64
* Contacts GPG keys looks good, not sure when Justin got verified?
* Certs protection with HSM story looks good
* Grub modules looks good, no NTFS module
* SBAT entry for grub looks good and it's grub,3 since no NTFS patches has been applied to their grub sources
* NX is disabled and doesn't exist in the boot chain

**Comment by jsetje** [comment] 2024-02-21 05:38
I did not spot any additional issues.

**Comment by SherifNagy** [comment] 2024-03-25 15:07
Can we close this if you got the shim singed back from MSFT?

**Closed** 2024-03-26 02:06 UTC
Labels: accepted
