### ISSUE TITLE
SHIM 15.4 for NComputing Global, Inc.

### ISSUE THREAD

**Issue by ncboot** [rhboot/shim-review#206] opened 2021-09-16 19:08 UTC
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag  
            https://github.com/ncboot/shim-review/tree/ncomputing-shim-x64-20220310v2
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed  
            https://github.com/ncboot/shim-review/blob/v15.4c/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)  
            https://github.com/ncboot/shim-review/blob/v15.4c/NC.cer
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )  
            no binaries
 - [x] any extra patches to shim via your own git tree or as files  
            no patches
 - [x] any extra patches to grub via your own git tree or as files  
            no patches
 - [x] build logs  
            https://github.com/ncboot/shim-review/blob/v15.4c/build.log
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries  
            https://github.com/ncboot/shim-review/blob/v15.4c/Dockerfile

###### What organization or people are asking to have this signed:
`[NComputing Global, Inc. ]`

###### What product or service is this for:
`[LEAF OS Linux software endpoint solution by NComputing. ]`

###### Please confirm this as the origin your shim.
`[yes, we use directly https://github.com/rhboot/shim/releases/tag/15.4]`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`[NComputing LEAF OS is a Linux software endpoint solution that transforms any x86-64 PC, laptop, or thin client into a secure and centrally managed endpoint to access popular desktop virtualization environments, including Microsoft Azure Virtual Desktop (AVD), Windows 365 Cloud PC, Microsoft Remote Desktop Services (RDS) and others.  
LEAF OS solution is available worldwide, covering education, SMB, SME and enterprise customers.   
LEAF OS endpoint solution addresses concerns related to security, corporate data leakage, patch management and central manageability for companies with working-from-home and BYOD initiatives using personal devices.  
A bootable USB memory stick can be created containing LEAF OS. Any x86-64 hardware device can secure boot to LEAF OS and instantly becomes a locked-down LEAF OS thin client. 
LEAF OS can be used to repurpose PCs and laptops by converting any x86-64 hardware from a stand-alone computer to a dedicated thin client by installing directly onto an internal hard drive and removing the old system and files.  
This method extends the usefulness of aging computers using end-of-life operating systems like Windows 7 while giving users powerful up-to-date desktops.  
NComputing would like customers to be able to run LEAFOS Linux endpoint on any x86-64 devices without disabling Secure Boot.]`

###### How do you manage and protect the keys used in your SHIM?
`[keys are on HW eToken (SafeNet eToken 5110 FIPS) kept by authorized persons]`

###### Do you use EV certificates as embedded certificates in the SHIM?
`[yes, we have EV certificate (file NC.cer in this repo) embedded into shim]`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`[vendor_db is not used]`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`[yes, our kernel has upstream commit "ACPI: configfs: Disallow loading ACPI tables when locked down" 75b0cea7bf307f362057cc778efe89af4c615354 applied]`

###### fixed ?
`[We use upstream GRUB 2.06 with all above CVEs fixed]`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`[Our GRUB2 has embedded SBAT section with following 3 lines:]`

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md  
grub,1,Free Software Foundation,grub,2.06,https://www.gnu.org/software/grub/  
grub.ncomputing,1,NComputing Global,grub,2.06,https://ncomputing.com  

##### Were your old SHIM hashes provided to Microsoft ?
`[No, this is first time submission, we have no older SHIMs]`

##### grub2 bootloaders can not be verified ?
`[We use upstream GRUB 2.06 trusting it's strategy]`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`[We use upstream GRUB 2.06 with SBAT section]`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`[GRUB https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz sha256 b79ea44af91b93d17cd3fe80bdae6ed43770678a9a5ae192ccea803ebb657ee1 grub-2.06.tar.xz]`

###### If your SHIM launches any other components, please provide further details on what is launched
`[No, shim launches GRUB only]`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`[GRUB2 lanches Kernel only]`

###### apply. Please describe your strategy.
`[This is first time submission, we do not have older GRUB2 binaries]`

###### How do the launched components prevent execution of unauthenticated code?
`[We use chained loading: shim -> grub2 -> kernel with all components signed ]`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`[No]`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`[Kernel 5.10]`

###### What changes were made since your SHIM was last signed?
`[This is first time submission]`

###### What is the SHA256 hash of your final SHIM binary?
`[3ac79c4370f14e444f036319de1c5fbb1fee098e14b6e16cc073b15aa9ef7c39]`

**Comment by julian-klode** [comment] 2021-10-06 09:01
- The SBAT component names are too short
- The shim-review repository is not forked from the main one
- In #211, the Amzetta submission is eerily similar to this one
- I don't know if kernel 5.4 contains all needed patches
- shim 15.4 misses several important patches and will not work correctly on a number of systems (#165)

**Comment by ncboot** [comment] 2021-10-06 14:30
1) SBAT entry changed from grub.nc to grub.ncomputing, Is it okay?
2) github.com/ncboot/shim-review repo now is forked from main one
3) no idea, why they copied this submission
4) which exactly kernel patches do You need? Our kernel has upstream commit "ACPI: configfs: Disallow loading ACPI tables when locked down" 75b0cea7bf307f362057cc778efe89af4c615354 applied, I checked sources manually for this patch.
Any other are neccesary?  Which one? Anyway meantime after submission we already switched to next kernel version 5.10
5) Dockerfile was modified to cherry-pick several critical commits. I need few days to check how it works now after those picked commits.

PS: to be honest I tried to follow exact instruction in README.md - it says:
**Please create your shim binaries starting with the 15.4 shim release tar file**
Probably You would modify this to something like 
**Please create your shim binaries starting with the 15.4 shim release tar file plus critical patches**
This may help other submitters. Otherwise I had false impression that important is to take exactly 15.4 tag.
Sorry.

**Comment by ncboot** [comment] 2021-11-24 08:21
Hi, is there anything we can do to expedite the review process? It has been a few months now and many of our customers (including many schools) are waiting for our secure environment.
Thanks for your help in advance.

**Comment by frozencemetery** [comment] 2021-11-24 15:32
While attempting email verification, I noticed that the keys are not available from keyservers.  Please push them and provide fingerprints in the README.

**Comment by ncboot** [comment] 2021-11-25 09:49
Hello
I pushed emails to https://pgp.mit.edu server and fingerprints are noted in README.md now.
This change tagged with "ncomputing-shim-x64-20211125"

**Comment by frozencemetery** [comment] 2021-12-13 19:40
I see fingerprints, but am unable to retrieve the keys.  Perhaps if you use a different keyserver, like keyserver.ubuntu.com?  The MIT one doesn't really work anymore.

**Comment by ncboot** [comment] 2021-12-14 02:12
Pub keys pushed to ubuntu key server.
Updated readme.
New tag ncomputing-shim-x64-20211214.
PS: Besides that, MIT key server works perfectly for me.

**Comment by ncboot** [comment] 2021-12-14 07:52
Can You please check my recent commit.

**Comment by marsohod4you** [comment] 2022-01-18 07:23
Happy New Year!
Do we all have any chance?

**Comment by ncboot** [comment] 2022-01-18 07:25
Hello! Can You please review?

**Comment by ncboot** [comment] 2022-01-27 10:31
Many of our customers (including many schools) are waiting for our secure boot support. We are planning to add the secure boot feature in the upcoming product release. Could you please expedite the review process as it has been several months? Thank you.

**Comment by frozencemetery** [comment] 2022-02-03 23:59
I am going to send you some words.  When you receive them, please post them here.

**Comment by ncboot** [comment] 2022-02-06 13:05
For the Shim words that was sent to fpesek@ncomputing.com, here is the decrypted text:

elektriskeste
h=C3=B8ststorm
solnedgangene
bondelagsformannens
striregnet
komplementerende
mindretallsposisjonen
massekultur
nattverdsbordene
frigruppene
katguter
originalgulvets
erkebispestol

For the Shim words that was sent to rsah@ncomputing.com, here is the decrypted text:

lovprisende
tegneatelieret
landkrabba
banel=C3=B8p
varmekildens
spanter
tredjest=C3=B8rste
danske
gallegr=C3=B8nest
kostnadsoversikter
trekkhjul
telefonfunksjon=C3=A6rens
enkeltvalutaen

**Comment by ecos-platypus** [comment] 2022-03-09 16:20
Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.

Review was conducted in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines)

The links in the issue point to a deleted tag, I conducted this review for the latest tag (`ncomputing-shim-x64-20211214`).

1. New vendor, contact verification has been conducted by @frozencemetery
2. I was able to reproduce the build via the Dockerfile. It may be useful to add a hexdump diff and sha256 checksum comparison to the Dockerfile to make comparison easier
3. Shim is built from upstream Git repository with the 15.4 tag checked out and regression patches cherry-picked, looks okay
4. Questions in issue template and README.md are answered
5. Embedded EV certificate matches the organization (`NComputing Global, Inc.`)
6. Keys are stored on `HW eToken (SafeNet eToken 5110 FIPS) `
7. The embedded EV certificate has an acceptable duration of 3 years
8. The submitted `shimx64.efi` binary does not contain SBAT data
    1. Only SBAT data for GRUB is listed in the issue template (with incorrect vendor `Free Software Foundation`), the too short vendor extension `nc` has been mentioned before and has been fixed in the shim-review fork but not in the issue text
    2. Build is not derived from other distro
9. GRUB is used as bootloader
10. Questions regarding GRUB
    1. Upstream GRUB 2.06 (includes CVE fixes) is used
    2. No custom patches are mentioned
11. Kernel 5.4 with lockdown patches is used
12. Not applicable, first submission
13. Shim verifies and loads GRUB, GRUB verifies and loads Kernel

Please address the issues regarding sbat data and update your submission accordingly.

**Comment by ncboot** [comment] 2022-03-10 09:44
To [ecos-platypus](https://github.com/ecos-platypus)
To be honest I was always thinking that this page issue submission text is not very important (because can be changed at any moment without any log), but important is shim-review fork because all steps are recorded, git logged there.

**Comment by ecos-platypus** [comment] 2022-03-10 09:59
As mentioned, you only list sbat entries for GRUB, sbat has to be embedded in shim and GRUB. As I said, your GRUB `grub.ncomputing` sbat entry lists `Free Software Foundation` as vendor which is incorrect as you are not the Free Software Foundation.

**Comment by ecos-platypus** [comment] 2022-03-10 10:37
The csv format of your GRUB sbat entry is invalid due to the additional comma in the vendor name. I am not going to repeat myself again regarding sbat data for shim and instead recommend you familiarize yourself with sbat: https://github.com/rhboot/shim/blob/main/SBAT.md

**Comment by ncboot** [comment] 2022-03-10 10:56
> The csv format of your GRUB sbat entry is invalid due to the additional comma in the vendor name. I am not going to repeat myself again regarding sbat data for shim and instead recommend you familiarize yourself with sbat: https://github.com/rhboot/shim/blob/main/SBAT.md

Shame on me.. Now fixed.

**Comment by ncboot** [comment] 2022-05-19 14:55
Is there anything our team can add/provide details to expedite the process?

**Comment by julian-klode** [comment] 2022-06-14 09:58
Closing outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.

**Closed by julian-klode** 2022-06-14 09:58 UTC
Labels: new vendor
