### ISSUE TITLE
Shim-15.5 for MicroWorld Technologies eScan for Windows

### ISSUE THREAD

**Issue by gv2870** [rhboot/shim-review#240] opened 2022-05-11 18:03 UTC
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [ ] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [ ] any extra patches to shim via your own git tree or as files
 - [ ] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
https://github.com/mwti/shim-review/tree/MicroWorld_Technologies-shim-x64-20220511
-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
40a1620f6e93a536f10776a93372aa64e4e4b8ca280870a8dac5ad714e685531

**Comment by ecos-platypus** [comment] 2022-05-12 06:49
Please use the ISSUE_TEMPLATE.md for requests and fill out all questions.

**Comment by ecos-platypus** [comment] 2022-05-12 09:13
Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.

Review was conducted in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines)

1. Vendor is new
    1. PGP public key fingerprints are missing in README
    2. PGP public keys should be published to https://keyserver.ubuntu.com/
2. Several issues with the build. It reproduces, but those issues should be fixed:
    1. Please rename `dockerfile.txt` to `Dockerfile`, this is the standard name for Dockerfiles and expected by tooling
    2. Please clone the `shim-review` fork for the build, currently `etoken.der`, sbat data and `shimx64.efi` are copied from https://github.com/mwti/rescueshim.git
3. Shim is built from upstream master (https://github.com/rhboot/shim.git is cloned but no tag never checked out). It should use the `15.5` tag
4. All questions in issue template and README.md are answered
5. Embedded EV certificate matches the company (`Subject: serialNumber = 802191518, jurisdictionC = US, jurisdictionST = Michigan, businessCategory = Private Organization, C = US, ST = Michigan, L = Novi, O = MicroWorld Technologies Inc., CN = MicroWorld Technologies Inc.`) and can be verified with Sectigo code sign ca certificates (`Sectigo Public Code Signing CA EV R36`, `SectigoPublicCodeSigningRootR46_AAA`)
6. `USB Token based 384-bit EV` sounds like hardware token which would be fine
7. The embedded EV certificate has a duration of 3 years which is acceptable
8. The submitted shim binaries contain the sbat data listed in README.md
    1. I am not sure about the vendor extension as the EV certificate is for `MicroWorld Technologies Inc` and I would assume that this is used as vendor rather than `eScan` which seems to be a specific product of the vendor
    2. GRUB build is based on Ubuntu and the Ubuntu entry correctly included in sbat data
9. GRUB 2.06 is used
10. GRUB-related questions:
    1. GRUB 2.06 is used and contains the CVE patches
    2. GRUB build is based on Ubuntu, no additional patches are mentioned
11. Linux Kernel 5.15.10 which includes the patches is used
12. Not applicable, first shim submission
13. Shim verifies GRUB, GRUB verifies kernel
    1. Please clarify the part `vmlinuz64 is based on kernel 2.06`, other sections mention Linux Kernel 5.15.10

**Comment by gv2870** [comment] 2022-05-12 13:44
Thank you for your efforts and taking out time to review.

We have made the following changes and commit has been done.

README.MD

1. PGP Public Key Fingerprints added for both contacts.

2. Public Keys published to https://keyserver.ubuntu.com

3. CLARIFICATION: vmlinuz64 is based on Linux Kernel 5.15.10 (erroneously written as 2.06)

4. Modified README.MD committed

REPO

1. dockerfile.txt renamed to Dockerfile

2. Dockerfile modified to clone from https://github.com/mwti/shim-review.git for etoken.der and sbat.csv 

3. Modified Dockerfile committed

YOUR QUERY

MicroWorld Technologies Inc. is vendor name and eScan is product/solution name.

**Comment by gv2870** [comment] 2022-05-12 15:18
Link to new tag (with updated Dockerfile and README.MD):
https://github.com/mwti/shim-review/tree/MicroWorld_Technologies-shim-x64-20220512

**Comment by ecos-platypus** [comment] 2022-05-13 05:58
I can now see the keys on https://keyserver.ubuntu.com, however the keys are not signed by the respective other security contact. Please do that and push the updated keys to the keyserver.

Regarding vendor/product naming: I guess the sbat data should then contain MicroWorld Technologies Inc. as vendor. `shim.eScan` is fine as shim is for this product. I guess this is kind of nit-picking, I leave this to an authorized reviewer to decide.

The other changes look good.

**Comment by gv2870** [comment] 2022-05-13 10:14
Thank you for your response.

Keys have now have been certified by respective other security contact & published.

**Comment by gv2870** [comment] 2022-05-18 10:43
Are there any queries for us?
Is there anything our team can add/provide details to expedite the process?
Do kindly let us know.
Thank you!

**Closed** 2022-06-14 09:57 UTC
Labels: new vendor, contact verification needed
