### ISSUE TITLE
NComputing LEAFOS shim-15.6 x64

### ISSUE THREAD

**Issue by ncboot** [rhboot/shim-review#279] opened 2022-08-26 12:26 UTC
Confirm the following are included in your repo, checking each box:

    [+] completed README.md file with the necessary information
    [+] shim.efi to be signed
    [+] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
    [-] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
    [-] any extra patches to shim via your own git tree or as files
    [-] any extra patches to grub via your own git tree or as files
    [+] build logs
    [+] a Dockerfile to reproduce the build of the provided shim EFI binaries

What is the link to your tag in a repo cloned from rhboot/shim-review?

https://github.com/ncboot/shim-review/tree/ncomputing-shim-x64-20220826
What is the SHA256 hash of your final SHIM binary?

[27e393d9f242d9cbcc0d4a939fce9c3d7ca85289a2aa498abcf651c532240488 shimx64.efi]

-------------------------------------------------------------------------------
### What is the link to your previous shim review request (if any, otherwise N/A)?
-------------------------------------------------------------------------------
[N/A]

**Comment by steve-mcintyre** [comment] 2022-09-02 00:04
contact verifications mails sent

**Comment by steve-mcintyre** [comment] 2022-09-02 00:29
Looking:
- shim build reproduces here
- shim builds from the upstream 15.6 tag in git, ok
- Includes a Digicert EV code signing cert, valid to end of 2023. A little short, but ok...
- SBAT data could do with a tweak (see below)
- no old builds to revoke, fine
- grub looks ok, straight from upstream
- your list of grub modules is *tiny* - is that really enough??
- upstream kernel 5.10.65 *might* be ok, but it's getting a little old (Septembet 2021)
- key managed in a hardware token, good

Things to check:
- Your SBAT entries for *your` builds should use generation 1, not 2. You don't need to increment from 1 just because upstream does - see the SBAT docs.
- Using a 5.10 series LTS kernel is fine, but I'd be worried that you're a little far back there. There's a *lot* of securty fixes that have been merged in the last year.
- Curious about the grub modules!

**Comment by ncboot** [comment] 2022-09-05 07:46
hi
1) Updated SBAT entires for shim and grub. Now they use generation 1
Repo with updates https://github.com/ncboot/shim-review tagged as ncomputing-shim-x64-20220905v2
New shim binary hash is 66658ad2cfa33a8b7f960da49731ae6325627630606254d6d08e9b8d02e8dcad
2) We use 5.10 kernel because for now it is fully compatible with our LEAFOS embedded thin clients and it is well proven in a fields by customers. For future we are working on kernel updates.
3) we are trying to keep minimal LEAFOS image size and remove all unnecessary components. Described grub2 module list is proven enough for us.

**Comment by steve-mcintyre** [comment] 2022-09-07 23:23
- new build reproduces fine
- SBAT entries look better, thanks!

all done!

**Comment by ncboot** [comment] 2022-09-08 08:47
Contact verification:
For the Shim words that were sent to fpesek@ncomputing.com, here is the decrypted text:

phantoms grackle faithlessness downgraded critiqued bus concubines Kankakee=
 feverish foreswearing

For the Shim words that were sent to rsah@ncomputing.com, here is the decrypted text:

reopening Heywood damaging tiled monosyllabic commonly sprain hasheesh weas=
els muzzles

**Comment by ncboot** [comment] 2022-09-23 07:14
got signed shim from MS

**Closed** 2022-09-23 07:14 UTC
Labels: accepted, new vendor
