### ISSUE TITLE
FYI: Microsoft's shim review

### ISSUE THREAD

**Issue by joseph-zeronsoftn** [rhboot/shim-review#128] opened 2020-12-14 23:33 UTC
We are also waiting for the sim review.
I tried submitting a shim directly to MS a while ago.
Then on November 25th, I received the following email from Microsoft.

> Currently, Microsoft is updating our SHIM Review process and therefore will not be approving any new SHIMs at this point. Once we finalize the new process, it will be published online for you to read.

There are no updates since then.

**Comment by jason-chang-atrust** [comment] 2021-01-05 06:10
If there's any updates, please inform us.
Many thanks.

**Comment by julian-klode** [comment] 2021-03-25 12:10
Duplicate of #120 

shim 15.3 is out now and we are slowly ramping up reviewing; but be aware that it's a priority queue and the big distros and vendors involved might jump ahead if you submit before them.

**Closed by julian-klode** 2021-03-25 12:10 UTC
