### ISSUE TITLE
SHIM 15+39b8345 for Serva

### ISSUE THREAD

**Issue by ppatpat** [rhboot/shim-review#32] opened 2018-09-01 15:32 UTC
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
ppatpat/shim-review@serva-shim-x64-ia32-15+39b834
 - [x] completed README.md file with the necessary information
see ppatpat/shim-review@serva-shim-x64-ia32-15+39b834
 - [x] shim.efi to be signed
see ppatpat/shim-review@serva-shim-x64-ia32-15+39b834  shimx64.efi shimia32.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
see ppatpat/shim-review@serva-shim-x64-ia32-15+39b834 PM_PubCert.der
 - [x] any extra patches to shim via your own git tree or as files
none
 - [x] any extra patches to grub via your own git tree or as files
Shim boots pxeserva.efi bootloader instead.
 - [x] build logs
see ppatpat/shim-review@serva-shim-x64-ia32-15+39b834  build_Serva_Shim_x64_15+39b8345.log build_Serva_Shim_ia32_15+39b8345.log

###### What organization or people are asking to have this signed:
`Vercot-Serva`

###### What product or service is this for:
`Serva 32/64`

###### What is the origin and full version number of your shim?
`15+39b8345`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`Serva is a well know PXE server`

###### How do you manage and protect the keys used in your SHIM?
`Vault/password protected only used when signing release versions `

###### Do you use EV certificates as embedded certificates in the SHIM?
`No`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`pxeserva.efi is a Pxelinux 6.03 derivative`

###### If your SHIM launchers any other components, please provide further details on what is launched
`No`

###### How do the launched components prevent execution of unauthenticated code?
`N/A`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`Only loads pxeserva.efi`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`-`

###### What changes were made since your SHIM was last signed?
`N/A`

###### What is the hash of your final SHIM binary?
`shimx64=3DB001A1523AEF2BBD122F37DB7DDC5D347811ACA0907C741FB6324E3FFA1518  
 shimia32=E1053A4477A225093E5C880A1CC6DA587816F6E307B2CFECD2431BE90B499327`

**Comment by cyphermox** [comment] 2018-09-05 14:41
How do we know that pxeserva.efi is secure, and avoids loading unauthenticated code itself? Presumably it can load any random thing from the network if it's a PXE client? If it's a PXE server, why not have that signed directly by Microsoft rather than first loading through shim?

**Comment by ppatpat** [comment] 2018-09-05 15:21
Hi, Serva has been around since 2010 and the current Secure Boot strategy is to offer for PXE boot just MS Boot Managers (bootmgfw.efi) but they lack many features requested by Serva users like Linux boot, password protected menu entries, sub-menus, colors, etc. You can browse the net and you won't find a single mention of Serva Boot Managers (pxeserva.efi) booting any kind of unauthorized code, Serva is a well behaved PXE server that only loads its own secure code and offers for net loading to PXE clients only the specified secure assets. Among Serva [users](https://www.vercot.com/~serva/references/references.html) you will find pretty big companies, the military and government. The shim strategy looked like a good compromise considering the MS lengthy signature process when needing to update Serva boot managers code and also the current lack of an "EV" certificate required for a MS direct signature request.  Thanks for your help.

**Comment by cyphermox** [comment] 2018-10-02 01:20
I think we're not completely understanding each other.

What technical steps are taken to ensure that pxeserva.efi does not load unauthorized code? (FWIW, this is a question requirement from Microsoft, I am unaware of how much attention they pay to this, and if they usually audit the code, etc.)

What we're concerned with is precisely loading code in a Secure Boot context when the code is unauthenticated, so we wouldn't see any such issues right now if it's only run when Secure Boot is disabled.

**Comment by cyphermox** [comment] 2018-10-02 02:49
I am unable to rebuild this, we're missing information. How did you get that gnu-efi build? Was it modified in any way? It doesn't look to be the one available on Debian. Did you build it yourself?

Was the ia32 build done on amd64 or elsewhere?

**Comment by ppatpat** [comment] 2018-10-02 17:36
1) 
Serva's server module file-locks its bootloaders preventing inadvertently offering unknown NBP code to booting PXE clients, Also Serva's EFI bootloaders check that kernels are properly signed before running them.

2) 
Shim/gnu-efi were built on a Debian GNU/Linux 9.3 64 Bit (stretch), 

gnu-efi:
I copied gnu-efi v3.0.8 source under ./shim-master/gnu-efi/gnu-efi-3.0.8/ 
ia32 compilation required adding  #include <stdint.h> to
**/lib/dpath.c**
**/lib/hand.c**  

then I built the gnu-efi library with
#make
#make ARCH=ia32

Shim:
The location of gnu-efi, and building ia32 required editing accordingly 
 **Make.defaults**  (altering DEFAULT_LOADER, EFI_INCLUDE, LIBDIR, EFI_PATH2, BITS, and LDFLAGS)

I also minimally edited 
 **Makefile** (preventing a "git clean" command giving an error, -no source control-)

No Shim source file was altered.

I compiled both architectures with:

#make clean
#make VENDOR_CERT_FILE=PM_PubCert.der >build64.log 2>&1

#make clean ARCH=ia32
#make VENDOR_CERT_FILE=PM_PubCert.der ARCH=ia32 >build32.log 2>&1

Note: I have committed both  **Make.defaults** and **Makefile** to 
https://github.com/ppatpat/shim-review
Changes are indicated with **#Patrick**

Thanks for your help.

**Comment by cyphermox** [comment] 2018-10-19 21:59
I am unable to reproduce this build, doesn't matter what I try.

Other submissions have been using a docker script to make the reproducibility easier. Is that something you could try, and ship the changes you need as patches, so we can reproducibly build this?

**Comment by ppatpat** [comment] 2018-10-29 17:34
Sorry the delay.
Please find the whole [shim build directory](https://mega.nz/#!xUVgkArC!ABVRyA8CiSeFcAy3SFW5khGXjynFZHdmXmbPsMBxd9U) including gnu-efi 3.0.8

from within /shim-master

#make clean
#make VENDOR_CERT_FILE=PM_PubCert.der >build64.log 2>&1

#make clean ARCH=ia32
#make VENDOR_CERT_FILE=PM_PubCert.der ARCH=ia32 >build32.log 2>&1

Please let me know
Thanks

**Comment by cyphermox** [comment] 2018-11-16 00:54
This is not starting a Linux-based bootloader (it does not load grub) and we have no way to ensure the next loaded image (your plugin infrastructure, etc.) is secure and enforcing the signatures on further loaded binaries.

It appears to me like this would be better served by having your plugin-based loader environment reviewed and signed by Microsoft directly rather than us sanctioning the use of shim to circumvent proper review procedures on loaded EFI applications as required by the Windows Hardware Dev Center for signature using Microsoft keys.

That one is a NAK from me -- it's not a Linux bootloader, it should get reviewed and signed by WHDC directly.

**Comment by ppatpat** [comment] 2018-11-16 15:33
Shim starts pxeserva.efi which is a Syslinux/Pxelinux 6.03 derivative as I've said it in the first post.
The structure is closed and does not offer "plug-in" facilities to end users. It's meant to finally boot only signed Microsoft "kernels" (bootmgfw.efi) and signed linux kernels (like grub does).

I started this process because it was simpler than MS' specially when considering that starting a new signing process would be required every time we have to recompile pxeserva.efi. There's no intention to circumvent any proper review here; as I've mentioned before Serva has been around for long time now and it is a serious application.

Thanks for your help.

**Comment by cyphermox** [comment] 2019-01-31 18:20
We're working with Microsoft at the time to figure out the correct way forward, stay tuned.

**Comment by ppatpat** [comment] 2019-08-12 15:07
Sorry for bothering; any news on this?
Thanks.

**Comment by julian-klode** [comment] 2020-09-22 18:22
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.

**Closed by julian-klode** 2020-09-22 18:22 UTC
Labels: custom second-stage
