### ISSUE TITLE
BitRaser-shim-X86_64-shim-15.4

### ISSUE THREAD

**Issue by bitraser** [rhboot/shim-review#175] opened 2021-05-26 05:04 UTC
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
         [bitraser/shim-review@bitraser-shim-x64-20220121](https://github.com/bitraser/shim-review/tree/bitraser-shim-x64-20220121)
 - [x] completed README.md file with the necessary information
        https://github.com/bitraser/shim-review/blob/bitraser-shim-x64-20220121/README.md
 - [x] shim.efi to be signed
        https://github.com/bitraser/shim-review/blob/bitraser-shim-x64-20220121/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
       https://github.com/bitraser/shim-review/blob/bitraser-shim-x64-20220121/stellar-pub.cer
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
        NA
 - [x] any extra patches to shim via your own git tree or as files
         Not applied any extra patch
 - [x] any extra patches to grub via your own git tree or as files
        No
 - [x] build logs
        https://github.com/bitraser/shim-review/blob/bitraser-shim-x64-20220121/build.log
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
         https://github.com/bitraser/shim-review/blob/bitraser-shim-x64-20220121/Dockerfile

###### What organization or people are asking to have this signed:
`[Stellar Information Technology Pvt Ltd]`

###### What product or service is this for:
`[BitRaser Data Eraser Software]`

###### Please confirm this as the origin your shim.
`[https://github.com/bitraser/shim/tree/bitraser-shim15-4  based on https://github.com/rhboot/shim/tree/shim-15.4]`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`[Stellar requires to employ secure boot for building trusted operating system. This OS has to be capable of booting every machine so that it can be used with BitRaser Data Eraser software]`

###### How do you manage and protect the keys used in your SHIM?
`[Cryptographic USB Token]`

###### Do you use EV certificates as embedded certificates in the SHIM?
`[YES]`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`[No vendor_db is used (this is first time submission]`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`[YES]`

###### fixed ?
`[Yes]`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`[sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
grub,1,Free Software Foundation,grub,2.06,https://www.gnu.org/software/grub/
shim-bitraser,1,Stellar Data Recovery Inc,bitraser,2.0,https://www.bitraser.com/
]`

##### Were your old SHIM hashes provided to Microsoft ?
`[This is first time submission]`

##### grub2 bootloaders can not be verified ?
`[Yes, Also using latest grub 2.06]`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`[Downstream RHEL/Fedora/Debian/Canonical like implementation]`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`[https://github.com/bitraser/grub2/tree/bitraser-grub2-6]`

###### If your SHIM launches any other components, please provide further details on what is launched
`[SHIM will only launch GRUB. No other component will be launched by the SHIM]`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`[SHIM WILL ONLY LAUNCH SIGNED GRUB AND KERNEL,grub verifies signatures on booted kernel.Arch linux kernel version is 5.7.11]`

###### apply. Please describe your strategy.
`[first time submission]`

###### How do the launched components prevent execution of unauthenticated code?
`[kernel,grub is signed and also updated with latest patch .it prevent unsigned module to launch]`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`[NO]`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`[Kernel Version is 5.7.11 it included enforce secure boot]`

###### What changes were made since your SHIM was last signed?
`[This is first time submission]`

###### What is the SHA256 hash of your final SHIM binary?
`[ce7e025f2ddb09ccc5be0c9515fb50c42465bac65a3b3220543a0a5c42047859  shimx64.efi]`

**Comment by bitraser** [comment] 2021-06-07 10:45
@steve-mcintyre 
Thanks for adding  labels.
Do you have any query or we need to apply any extra patch Please suggest.

**Comment by steve-mcintyre** [comment] 2021-06-21 22:39
Sorry to keep you waiting - I don't have much time at the moment.

I can see that you've forked the shim-review repository on githib, but I don't see a branch there with your full submission. Please take a look at some of the other submissions for examples of the kind of thing we're looking for. (I'll suggest my own submission here - see the branches and tags on https://github.com/steve-mcintyre/shim-review/ for the Debian shim submissions I made)

**Comment by bitraser** [comment] 2021-06-24 08:10
@steve-mcintyre we  have created a branch and tagged it and details has been updated.
https://github.com/bitraser/shim-review-15.4/releases/tag/BitRaser-3-shim-x64-20210624

**Comment by steve-mcintyre** [comment] 2021-06-27 23:14
Getting better, but still not there yet. How can I reproduce your build? Check the other review submissions for examples - the preferred route is to provide a Dockerfile which a reviewer can use. That gives us confidence i your build output, patches etc.

**Comment by julian-klode** [comment] 2021-06-28 14:30
I'm not convinced the submitters are capable of providing a secure boot environment. The quality of the submission with the typos and ignorance of the questions asked, as below, makes me very concerned.

```
What OS and toolchain must we use to reproduce this build? Include where to find it, etc. We're going to try to reproduce your build as close as possible to verify that it's really a build of the source tree you tell us it is, so these need to be fairly thorough. At the very least include the specific versions of gcc, binutils, and gnu-efi which were used, and where to find those binaries. If the shim binaries can't be reproduced using the provided Dockerfile, please explain why that's the case and the differences would be.
[BitRaser OS is a customized OS using arch linux.]
```

**Comment by steve-mcintyre** [comment] 2021-06-28 16:31
> I'm not convinced the submitters are capable of providing a secure boot environment. The quality of the submission with the typos and ignorance of the questions asked, as below, makes me very concerned.
> 
> ```
> What OS and toolchain must we use to reproduce this build? Include where to find it, etc. We're going to try to reproduce your build as close as possible to verify that it's really a build of the source tree you tell us it is, so these need to be fairly thorough. At the very least include the specific versions of gcc, binutils, and gnu-efi which were used, and where to find those binaries. If the shim binaries can't be reproduced using the provided Dockerfile, please explain why that's the case and the differences would be.
> [BitRaser OS is a customized OS using arch linux.]
> ```

maybe, let's see...

**Comment by bitraser** [comment] 2021-07-06 06:51
> Getting better, but still not there yet. How can I reproduce your build? Check the other review submissions for examples - the preferred route is to provide a Dockerfile which a reviewer can use. That gives us confidence i your build output, patches etc.

@steve-mcintyre  we have created docker file to reproduce build and updated the submissions along with the questions asked. Kindly review it again.

**Comment by bitraser** [comment] 2021-07-06 06:52
> I'm not convinced the submitters are capable of providing a secure boot environment. The quality of the submission with the typos and ignorance of the questions asked, as below, makes me very concerned.
> 
> ```
> What OS and toolchain must we use to reproduce this build? Include where to find it, etc. We're going to try to reproduce your build as close as possible to verify that it's really a build of the source tree you tell us it is, so these need to be fairly thorough. At the very least include the specific versions of gcc, binutils, and gnu-efi which were used, and where to find those binaries. If the shim binaries can't be reproduced using the provided Dockerfile, please explain why that's the case and the differences would be.
> [BitRaser OS is a customized OS using arch linux.]
> ```

@julian-klode  we have reviewed the submission and questions asked. we have updated them accordingly. Kindly verify it and let me know if any other updates required.

**Comment by steve-mcintyre** [comment] 2021-07-12 23:41
Problems during docker build:

```
Step 7/12 : RUN         git clone --recursive -b shim-15.4 https://github.com/bitraser/shim.git shim
 ---> Running in 8fa993b0446d
Cloning into 'shim'...
fatal: Remote branch shim-15.4 not found in upstream origin
The command '/bin/sh -c git clone --recursive -b shim-15.4 https://github.com/bitraser/shim.git shim' returned a non-zero code: 128
```

**Comment by bitraser** [comment] 2021-07-13 17:34
@steve-mcintyre   Please use Docker files as in issue template.
https://github.com/bitraser/shim-review-15.4/tree/BitRaserOS-shim-15.4   This repo contain all necessary files and docker file.
docker file url:- https://github.com/bitraser/shim-review-15.4/blob/BitRaserOS-shim-15.4/Dockerfile

**Comment by steve-mcintyre** [comment] 2021-07-13 23:08
I'd updated on your master branch and that Dockerfile showed the problem I listed. Checking again now, I can see that you're still updating things on the branch and now there's a new tag that you've not mentioned here at all:

BitRaser-3-shim-x64-20210703

Should I be looking at that? Please be clear about what you're doing, and follow the guidance you've been given. I'm losing patience here as a volunteer...

**Comment by bitraser** [comment] 2021-07-14 08:11
@steve-mcintyre 
Apologize for the inconvenience as previously frequently updated after submission. we will not update anything further without your suggestion.

we haved not updated since 20210703 IST tag "BitRaser-3-shim-x64-20210703" created from branch "BitRaserOS-shim-15.4" from repository "shim-review-15.4" except updated in "README.md"
As commit https://github.com/bitraser/shim-review-15.4/commit/3dbb01f7a5bc9865956f83c4c03a81f462c85c52

we are not using "master" branch in repository "shim-review-15.4". we are using "BitRaserOS-shim-15.4" branch. 
Please suggest if require to update master branch from BitRaserOS-shim-15.4 or need to make default branch as "BitRaserOS-shim-15.4"

**Comment by bitraser** [comment] 2021-08-24 05:18
@steve-mcintyre 
Kindly review the submission and suggest if any changes are required.

**Comment by bitraser** [comment] 2021-10-12 03:16
@julian-klode 
Kindly review the submission and suggest if any changes are required.

**Comment by frozencemetery** [comment] 2021-12-13 19:26
The first instruction that you've marked as checked states:

>  link to your code branch cloned from rhboot/shim-review in the form user/repo@tag

- Your repo is not a fork
- Your link is not a tag

**Comment by bitraser** [comment] 2021-12-15 18:42
@frozencemetery Thanks for update.
we will create repo from fork and make changes as per your suggestion.

**Comment by bitraser** [comment] 2022-01-24 06:10
@frozencemetery , I have updated the submission. Now repo has been forked and tagged.
Please review it.

**Comment by frozencemetery** [comment] 2022-02-03 21:54
Hello, I'm going to send you each some words over email.  When you receive them, please post them here.

**Comment by bitraser** [comment] 2022-02-04 08:03
@frozencemetery, We have received emails on mukeshk@stellarinfo.com and skuljeet@stellarinfo.com.
Both mails has subject "shim word". But there is no any word in mail body. Although there are two attachments, one is "AT00001" with "Version: 1" text and another is "AT00002.bin" containg a PGP signature key.

I request you to send mail again with words.

**Comment by bitraser** [comment] 2022-02-04 20:51
@frozencemetery Please find below keyword as received.
------------------------------------
Kuljeet Singh <skuljeet@stellarinfo.com>
----------------------------------
mellomleder
fiskeartikler
solidaritetsb=C3=B8lga
parallellkobling
skalldatering
ford=C3=B8r
terrengforholdet
omsorgspersonen
Torgerssen
arbeidsterapier
mandeldeigene
amfibiefart=C3=B8yer
etyde

-----------------------------------
Mukesh Kumar <mukeshk@stellarinfo.com>
-----------------------------------
garantiavtaler
panikktiltakets
kretsmesterskapets
spesialplasser
statsteoretiker
Balkan-land
isbj=C3=B8rnkraniet
eiendomsdirektoratet
annetsteds
vakthuset
paternosterheiser
kronesalgene
glidest=C3=B8pinga

**Comment by frozencemetery** [comment] 2022-02-04 21:10
Modulo encoding issues, those match.

**Comment by bitraser** [comment] 2022-02-11 18:41
@frozencemetery is anything pending from our end ?
Please comment.

**Comment by frozencemetery** [comment] 2022-02-11 18:53
shim reviews are intended to be collaboratively done amongst distro vendors.  The idea is that we provide a check on each other to ensure quality.  This is not a service that "you" pay "us" for: there is no separation between the two.  Most of us are overworked, and badgering those who can find time to do reviews at all only punishes us for trying - without offering any assistance of your own.  If you want your submission done sooner, the best thing to do is make sure it is of good quality, and to
[review](https://github.com/rhboot/shim/wiki/reviewer-guidelines) those of others.

**Comment by ecos-platypus** [comment] 2022-03-09 10:38
Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.

I started reviewing this submissing in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines). However, there are multiple basic issues so that I recommend you to take a look at the reviewer guidelines yourself before you re-submit or update your submission.

A number of things I noticed:
- Dockerfile does not compare the built binary to the shim binary submitted in your shim-review fork
- Code Signing certificate expires in a few months
```
Validity
    Not Before: Jul  1 00:00:00 2019 GMT
    Not After : Jun 29 23:59:59 2022 GMT
```
- Sbat data is completely mixed up. One sbat file for shim and grub is not how it works, sbat data has the wrong format (should be `shim.bitraser`) and wrong version number: `shim-bitraser,1,Stellar Data Recovery Inc,bitraser,2.0,https://www.bitraser.com/`
- Please add more details regarding the `Cryptographic USB Token` used to secure the keys

While it may be harsh, the way it is right now, I do not find the submission to be of an acceptable quality.

**Comment by bitraser** [comment] 2022-03-23 02:49
@ecos-platypus , we are renewing certificate, once get updated certificate we will regenerate shim binary and update accordingly.

**Comment by julian-klode** [comment] 2022-06-14 09:55
Closing outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.

**Closed by julian-klode** 2022-06-14 09:55 UTC
Labels: new vendor
