### ISSUE TITLE
Oracle Linux 8.3 shim-15.3-1.0.1.el8 20210325

### ISSUE THREAD

**Issue by iokomin** [rhboot/shim-review#135] opened 2021-03-25 16:26 UTC
Make sure you have provided the following information:

 - [v] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [v] completed README.md file with the necessary information
 - [v] shim.efi to be signed
 - [v] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [v] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [v] any extra patches to shim via your own git tree or as files
 - [v] any extra patches to grub via your own git tree or as files
 - [v] build logs

###### What organization or people are asking to have this signed:
Oracle Corporation

###### What product or service is this for:
Oracle Linux
https://www.oracle.com/linux/index.html

###### Please confirm this as the origin your shim.
Upstream shim version 15.3
https://github.com/rhboot/shim/tree/shim-15.3

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:

Oracle Linux is a popular enterprise Linux distribution with Secure Boot support.

###### How do you manage and protect the keys used in your SHIM?

Digicert SSM service hardware protected EV certificates

###### Do you use EV certificates as embedded certificates in the SHIM?

Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?

No hashes whitelisted

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?

Yes

###### fixed ?

Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

We keep all upstream SBAT entries and also append Oracle specific.
Since most packages in Oracle Linux are based on RHEL we also keep RHEL specific entries.

Oracle specific additions to packages are

grub2 Oracle Linux 7:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.02,https://www.gnu.org/software/grub/
grub.rhel7,1,Red Hat Enterprise Linux 7,grub2,@@VERSION@@,mail:secalert@redhat.com
grub.ol7,1,Oracle Linux 7,grub2,@@VERSION@@,mail:secalert_us@oracle.com

grub2 Oracle Linux 8:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.02,https://www.gnu.org/software/grub/
grub.rhel8,1,Red Hat Enterprise Linux 8,grub2,@@VERSION@@,mail:secalert@redhat.com
grub.ol8,1,Oracle Linux 8,grub2,@@VERSION@@,mail:secalert_us@oracle.com

shim Oracle Linux 7:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.ol7,1,UEFI shim,shim,1,https://github.com/rhboot/shim

shim Oracle Linux 8:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.ol8,1,UEFI shim,shim,1,https://github.com/rhboot/shim

All new UEFI binaries that are yet to be built with SBAT support will follow agreed SBAT variable pattern and we will add Oracle specific entry for them.

##### Were your old SHIM hashes provided to Microsoft ?

Yes

##### grub2 bootloaders can not be verified ?

Affected grub2 signing cert removed from shim, new signing EV certificate introduced.
New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?

Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?

grub2 v2.02-90.0.2.el8 - upstream plus number of patches from RedHat and Oracle

###### If your SHIM launches any other components, please provide further details on what is launched

No

###### please provide further details on what is launched and how it enforces Secureboot lockdown

grub2 launches Linux kernel

###### How do the launched components prevent execution of unauthenticated code?
grub2 verifies signatures on booted kernels via shim

###### apply. Please describe your strategy.

Not applicable, grub2 leaf certificate rotated in Oracle Linux shim

###### How do the launched components prevent execution of unauthenticated code?

Oracle Linux has same UEFI verification shim framework as RHEL that verifies all launched UEFI binaries.
All modules built into the GRUB2 either use shim framework or disabled when secureboot is enabled.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

4.18 based kernel with lockdown patches
5.4 based kernel with lockdown patches
5.8 based kernel with lockdown patches

###### What changes were made since your SHIM was last signed?

Shim rebased to upstream version shim-15.3
Updated vendor_db certificates

###### What is the SHA256 hash of your final SHIM binary?

a3e392a05f0f90b3a349029b0824c0ab5f4e4919be3ff3e3fb3d558dc35e3a41  shimia32.efi
a0908092ddb7d1416e58a1aacd614f9047730f28fae916f1deed3adbe970882e  shimx64.efi

Link to review tag: https://github.com/iokomin/shim-review/tree/oracle-shim-15.3-1.0.1.el8-x86_64-20210325

**Comment by julian-klode** [comment] 2021-03-25 17:18
Review: OK
- the binaries match my rebuild
- sbat values match the ones specified
- The review questions seem good, sbat value seems good too.

concerns:
- I have *not* investigated any grub code, I did not see a link, but I'd assume it's the same as RHEL; if that's the case, that's good enough for me.

comments:
I'd suggest using a company team for future shim submissions such that there is a continuous repository for all (future) submissions.

**Comment by iokomin** [comment] 2021-03-25 17:33
@julian-klode yes our grub2 built on top of latest errata from RHEL. Latest OL8 grub2 srpm version:
http://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64/getPackageSource/grub2-2.02-90.0.2.el8_3.1.src.rpm

> I'd suggest using a company team for future shim submissions such that there is a continuous repository for all (future) submissions
Absolutely agree and I'll sort it out. As a sanity check for the filer, he should be in github Oracle org.

**Comment by aburmash** [comment] 2021-03-25 17:45
the delta is several patches on top of RHEL source:
Patch1001: bug18504756-use-different-title-for-UEK.patch
Patch1002: bug26388226-update-redhat-references.patch
Patch1003: bug29875597-Update-EFIDIR-in-several-grub2-additional-tools.patch
Patch1004: bug32063327-set-proper-blsdir-if-boot-is-on-btrfs-rootfs.patch


None of those patches actually touch any grub code ( except for shell scripts ) and do NOT modify any existing secureboot verification framework.

**Comment by aburmash** [comment] 2021-03-25 18:18
https://git.centos.org/rpms/grub2/tree/c8

**Comment by julian-klode** [comment] 2021-03-26 11:29
:heavy_check_mark: grub delta is good

**Comment by iokomin** [comment] 2021-03-26 18:46
vendor_db certs available in the corresponding review tag: https://github.com/iokomin/shim-review/tree/oracle-shim-15.3-1.0.1.el8-x86_64-20210325

**Comment by steve-mcintyre** [comment] 2021-03-26 18:55
Builds reproducibly here - good!

**Comment by steve-mcintyre** [comment] 2021-03-26 18:57
minor nit -your SBAT vendor entries don't point to anything you own. I know it's just a comment, but...

**Comment by steve-mcintyre** [comment] 2021-03-26 19:02
what's the file oraclegrubcer.cer used for?

**Comment by aburmash** [comment] 2021-03-26 19:42
> what's the file oraclegrubcer.cer used for?

that is public part of the grub certificate that is embedded in shim.
It is included in grub src.rpm for reference.
The one included in http://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64/getPackageSource/grub2-2.02-90.0.2.el8_3.1.src.rpm is the OLD certificate.

As soon as we issue new shim, new grub will be issued, signed by new cert, and new grub src.rpm will have certificate matching the public part that we include in matching shim.

**Comment by steve-mcintyre** [comment] 2021-03-26 20:46
ok, cool

**Comment by steve-mcintyre** [comment] 2021-03-26 20:53
grub looks ok to me

**Comment by steve-mcintyre** [comment] 2021-03-26 20:53
shim and certs look good together. All good here for me.

**Comment by julian-klode** [comment] 2021-03-29 17:32
Due to some further issues, 15.3 was not sufficient, hence removing accepted and adding wontfix.

**Closed** 2021-03-29 17:32 UTC
Labels: wontfix
