### ISSUE TITLE
2018-03-04 Isoo

### ISSUE THREAD

**Issue by haobinnan** [rhboot/shim-review#13] opened 2018-03-04 11:38 UTC
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files 
 - [x] any extra patches to grub via your own git tree or as files 
 - [x] build logs
###### What organization or people are asking to have this signed:
秦皇岛易之数软件开发有限公司
Isoo (Qinhuangdao) software development Co., Ltd.
Qinhuangdao, Hebei, China
Isoo is a software developer for data recovery, disk utilities and system backup.
Managing Director: Hao Binnan

###### Version of shim:
https://github.com/rhboot/shim/tree/14
Version: 14

###### Sysdev Submission ID:
ID: 2006375 (Name: shimia32_isoouefiboot_20180224)
ID: 2006374 (Name: shimx64_isoouefiboot_20180224)

###### What product or service is this for:
This is Isoo’s Linux-based operating system. We are going to develop some function based on the OS, such as resize partition, back up & restore operating system, etc.

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Isoo wants to employ Secure Boot for building a trusted operating system from Shim to GRUB to the kernel to signed filesystem partitions. Secure Boot is the first step for this.
Isoo would like customers to be able to run Isoo’s Linux-based system on any amd64(64Bit) and x86(32Bit) device without disabling Secure Boot.

https://github.com/haobinnan/shim-review/tree/isoo-shim-20180312

**Comment by haobinnan** [comment] 2018-03-07 03:51
@mjg59 @cyphermox @liulang

**Comment by haobinnan** [comment] 2018-03-09 03:34
Could you please review our submission? May I know how long this reviewing process may take?
@mjg59 @cyphermox

**Comment by vathpela** [comment] 2018-04-10 20:49
So... a couple of things:
1) you're going to need to have some kernel patches.  I've made a 4.14 tree that has the normal Secure Boot patchset applied here: https://github.com/vathpela/linux/tree/secure-boot-4.14 . Running "git format-patch v4.14.." should do the right thing.
2) I'm having some trouble reproducing either build - can you provide build instructions?  What's the make command line you used?  If this came from packaging, can you show me how to do the packaged build instead of trying to do it directly with make?

**Comment by haobinnan** [comment] 2018-04-10 21:00
hi @vathpela
Compile the shim command?

**Comment by vathpela** [comment] 2018-04-10 21:47
Yes, that's what I'm wondering - I can't make the ia32 build actually produce a resulting binary, and I'm wondering if it's something about my 'make' invocation.

**Comment by haobinnan** [comment] 2018-04-10 21:55
sudo apt install gnu-efi
sudo apt install gnu-efi:i386
--------------------------------------------------------------------

#!/usr/bin/env bash

Make="make -j$(cat /proc/cpuinfo | grep "cpu cores" | wc -l)"

if [ ! -f ../VariableSetting ]; then
    echo "Error: VariableSetting file does not exist ."
    exit 1
fi

#Load from VariableSetting file
AtomLinux_ShimVNumber="$(grep -i ^AtomLinux_ShimVNumber ../VariableSetting | cut -f2 -d'=')"
AtomLinux_cer="$(grep -i ^AtomLinux_cer ../VariableSetting | cut -f2 -d'=')"
#Load from VariableSetting file

#Use Existing Certificate  (yes | no)
UseExistingCertificate=yes
#Use Existing Certificate  (yes | no)

if [ $UseExistingCertificate = "yes" ]; then
    if [ ! -f ../certificate/$AtomLinux_cer ]; then
        echo "Error: VendorCertfile does not exist ."
        exit 1
    fi
fi

OBJ_PROJECT=shim
FILENAME=${AtomLinux_ShimVNumber}.tar.gz

#Download Source Code
if [ ! -f ./${FILENAME} ]; then
    #Check if necessary tools are installed
    if [ -z $(which wget) ]; then
        echo "wget is not installed."
        exit 1
    fi
    #Check if necessary tools are installed
    wget https://github.com/rhboot/shim/archive/${FILENAME}
    if [ ! $? -eq 0 ]; then
        echo "Error: Download shim ."
        exit 1
    fi
    #Check if it is downloaded successfully
    if [ ! -f ./${FILENAME} ]; then
        echo "Error: Download shim ."
        exit 1
    fi
fi
#Download Source Code

rm -rf ./${OBJ_PROJECT}_result
mkdir ${OBJ_PROJECT}_result
mkdir ${OBJ_PROJECT}-tmp
tar xzvf ./${FILENAME} -C ./${OBJ_PROJECT}-tmp
#Check Decompression
if [ ! $? -eq 0 ]; then
    echo "Error: Decompression shim ."
    exit 1
fi
#Check Decompression

cd ./${OBJ_PROJECT}-tmp/${OBJ_PROJECT}-${AtomLinux_ShimVNumber}

#Compile special treatment (Ubuntu OS?)
sed -i 's/?= $(LIBDIR)\/gnuefi/?= $(LIBDIR)/g' ./Makefile
#Compile special treatment (Ubuntu OS?)

#cp -v ../../make-certs ./

#function
function build()
{
    ARCH=$1
    NAME=$2
    if [ $UseExistingCertificate = "yes" ]; then
        echo | $Make ARCH=$ARCH VENDOR_CERT_FILE=../../../certificate/$AtomLinux_cer 2>&1 | tee ../../shim_build_${NAME}.log
    else
        echo | $Make ARCH=$ARCH ENABLE_SHIM_CERT=1
    fi
    #Check make
    if [ ! $? -eq 0 ]; then
        echo "Error: make (shim) ."
        exit 1
    fi
    #Check make

    cp -v ./*${NAME}.efi ../../${OBJ_PROJECT}_result/
    cp -v ./*${NAME}.efi.* ../../${OBJ_PROJECT}_result/
}
#function

#x86
# make clean
sed -i 's/$(shell $(CC) -print-libgcc-file-name)/$(shell $(CC) -m32 -print-libgcc-file-name)/g' ./Makefile
build ia32 ia32
#Check build
if [ ! $? -eq 0 ]; then
    echo "Error: build ."
    exit 1
fi
#Check build
sed -i 's/$(shell $(CC) -m32 -print-libgcc-file-name)/$(shell $(CC) -print-libgcc-file-name)/g' ./Makefile
#x86

echo "-------------------------------------------------------------"

#x86_64
make clean
sed -i 's/$(shell $(CC) -print-libgcc-file-name)/$(shell $(CC) -m64 -print-libgcc-file-name)/g' ./Makefile
build x86_64 x64
#Check build
if [ ! $? -eq 0 ]; then
    echo "Error: build ."
    exit 1
fi
#Check build
sed -i 's/$(shell $(CC) -m64 -print-libgcc-file-name)/$(shell $(CC) -print-libgcc-file-name)/g' ./Makefile
#x86_64

#Copy Certificate
if [ $UseExistingCertificate = "no" ]; then
    mkdir ../../${OBJ_PROJECT}_result/certificate/
    cp -v ./*.pem *.p12 *.key *.csr *.crt *.cer ../../${OBJ_PROJECT}_result/certificate/
fi
#Copy Certificate

#clean
cd ../../
rm -rf ${OBJ_PROJECT}-tmp
#clean

echo "Complete."

**Comment by vathpela** [comment] 2018-04-10 22:11
Are you sure the ia32 build was built using gnu-efi 3.0.2-1ubuntu1?  I ask because that version doesn't appear to include the patch that makes it use its own implementations of __umoddi3() and __udivdi3(), and so when I'm building I get:
ld -o shimia32.so --hash-style=sysv -nostdlib -znocombreloc -T /root/haobinnan/shim/elf_ia32_efi.lds -shared -Bsymbolic -L/usr/lib32/ -L/usr/lib32/ -LCryptlib -LCryptlib/OpenSSL /usr/lib32//crt0-efi-ia32.o --build-id=sha1  --no-undefined shim.o netboot.o cert.o replacements.o tpm.o version.o errlog.o Cryptlib/libcryptlib.a Cryptlib/OpenSSL/libopenssl.a lib/lib.a -lefi -lgnuefi --start-group Cryptlib/libcryptlib.a Cryptlib/OpenSSL/libopenssl.a --end-group /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a 
/usr/lib32//libefi.a(math.o): In function `DivU64x32':
(.text+0x95): undefined reference to `__umoddi3'
/usr/lib32//libefi.a(math.o): In function `DivU64x32':
(.text+0xaa): undefined reference to `__udivdi3'
Makefile:203: recipe for target 'shimia32.so' failed
make: *** [shimia32.so] Error 1

**Comment by haobinnan** [comment] 2018-04-10 22:17
cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
--------------------------
apt list | grep "gnu-efi"
gnu-efi/xenial 3.0.2-1ubuntu1 amd64

**Comment by haobinnan** [comment] 2018-04-10 22:37
Please check the mail

**Comment by haobinnan** [comment] 2018-04-10 22:43
hi @vathpela
Please check the mail

**Comment by haobinnan** [comment] 2018-04-19 22:26
hi @vathpela
Please check the mail

**Comment by haobinnan** [comment] 2018-04-28 05:37
@vathpela  shim15: https://github.com/rhboot/shim-review/issues/17

**Comment by cyphermox** [comment] 2018-06-13 19:31
Closing, this would be a request superseded by a newer for shim 15.

**Closed by cyphermox** 2018-06-13 19:31 UTC
