### ISSUE TITLE
 SHIM 15.4 for AmZetta Technologies, LLC

### ISSUE THREAD

**Issue by amzdev0401** [rhboot/shim-review#211] opened 2021-10-06 02:54 UTC
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
  https://github.com/amzdev0401/shim-review/tree/AmZettaTech-shim-X86_64-shim-15.4
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 https://github.com/amzdev0401/shim-review/blob/AmZettaTech-shim-X86_64-shim-15.4/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 https://github.com/amzdev0401/shim-review/blob/AmZettaTech-shim-X86_64-shim-15.4/AMZ.cer
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 no binaries
 - [x] any extra patches to shim via your own git tree or as files
 no patches
 - [x] any extra patches to grub via your own git tree or as files
 no patches 
 - [x] build logs
 https://github.com/amzdev0401/shim-review/blob/AmZettaTech-shim-X86_64-shim-15.4/build.log
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
 https://github.com/amzdev0401/shim-review/blob/AmZettaTech-shim-X86_64-shim-15.4/Dockerfile

###### What organization or people are asking to have this signed:
`[AmZetta Technologies, LLC, For more info https://amzetta.com/ztc/]`

###### What product or service is this for:
`[SnapVDI Thin Client (zTC)-ENDPOINT DEVICES Hardware Thin client product. Powerful hardware components and native compatibility with VMware, Citrix, and Microsoft, as well as Azure and AWS cloud platforms, the AmZetta zTC thin client device seamlessly integrates into virtually any IT environment. Using the included AmZetta Client Manager (SCM) software, administrators can manage, monitor, and secure their entire zTC deployment from a single intuitive interface. More than ever before, businesses today need the ability to adapt to unforeseen circumstances. Equip your company with the agility to adapt without compromising power, compatibility, or security with the AmZetta zTC thin client. For More info: https://amzetta.com/ztc/]`

###### Please confirm this as the origin your shim.
`[yes, our repo https://github.com/amzdev0401/shim.git, tag Ver-15.4, is copy of https://github.com/rhboot/shim/releases/tag/15.4]`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`[Snap OS (TAILORED FOR VIRTUAL SPACES from Linux distribution) for Linux software endpoint solution by AmZetta Technologies. Snap OS is currently used in Hardware thin clients(zTC), It can be used to Repurposing the old laptop and desktops without any hassle. AmZetta Technologies would like customers to be able to run Snap OS Linux endpoint on any x86-64 devices without disabling Secure Boot.]`

###### How do you manage and protect the keys used in your SHIM?
`[[Hardware security module]`

###### Do you use EV certificates as embedded certificates in the SHIM?
`[yes, Amzetta generated self-signed certificate using OpenSSL embedded into shim]`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`[vendor_db is not used]`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`[yes, Kernel 5.10 is used in SnapOS. Kernel 5.10 has "ACPI: configfs: Disallow loading ACPI tables when locked down" fix]`

###### fixed ?
`[We use upstream GRUB 2.06 with all above CVEs fixed]`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`[Our SHIM has embedded SBAT section with following 3 lines:]`
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.amzetta,1,SnapOS,shim,15.4,https://amzetta.com

`[Our GRUB2 has embedded SBAT section with following 3 lines:]`
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.06,https://www.gnu.org/software/grub/
grub.amzetta,1,SnapOS,grub2,2.06,https://amzetta.com

##### Were your old SHIM hashes provided to Microsoft ?
`[No, this is first time submission, we have no older SHIMs]`

##### grub2 bootloaders can not be verified ?
`[We use upstream GRUB 2.06 trusting it's strategy]`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`[We use upstream GRUB 2.06 with SBAT section]`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`[GRUB https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz sha256 b79ea44af91b93d17cd3fe80bdae6ed43770678a9a5ae192ccea803ebb657ee1 grub-2.06.tar.xz]`

###### If your SHIM launches any other components, please provide further details on what is launched
`[No, shim launches GRUB only]`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`[GRUB2 launches Kernel only]`

###### apply. Please describe your strategy.
`[This is first time submission, we do not have older GRUB2 binaries]`

###### How do the launched components prevent execution of unauthenticated code?
`[We use chained loading: shim -> grub2 -> kernel with all components signed]`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`[No]`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`[Kernel 5.10]`

###### What changes were made since your SHIM was last signed?
`[This is first time submission]`

###### What is the SHA256 hash of your final SHIM binary?
`[f8f35ad9fec3763b45eae7beaab74eb3d006f3eb94f7382dd1290dd488200980]`

**Comment by julian-klode** [comment] 2021-10-06 08:50
This submission is inappropriate, it hijacks the ubuntu namespace. Surely you are aware that there already is an ubuntu vendor? It probably should use a `.amzetta` suffix.

The repositories are not forks of the main ones, but hand-stitched together, so to speak. Please rebase the repositories on top of the official ones, so that any changes can be clearly identified.

I do not know if linux 5.10 contains all necessary fixes.

**Comment by julian-klode** [comment] 2021-10-06 08:55
I'm confused because this just seems a copy-paste job of #206

**Comment by amzdev0401** [comment] 2021-10-06 12:39
> This submission is inappropriate, it hijacks the ubuntu namespace. Surely you are aware that there already is an ubuntu vendor? It probably should use a `.amzetta` suffix.
> 
> The repositories are not forks of the main ones, but hand-stitched together, so to speak. Please rebase the repositories on top of the official ones, so that any changes can be clearly identified.
> 
> There is no tag as required.
> 
> I do not know if linux 5.10 contains all necessary fixes.



> This submission is inappropriate, it hijacks the ubuntu namespace. Surely you are aware that there already is an ubuntu vendor? It probably should use a `.amzetta` suffix.
> 
> The repositories are not forks of the main ones, but hand-stitched together, so to speak. Please rebase the repositories on top of the official ones, so that any changes can be clearly identified.
> 
> There is no tag as required.
> 
> I do not know if linux 5.10 contains all necessary fixes.



Thank you, We will fix all mentioned issues. Linux 5.10 kernel has the fix for
"ACPI: configfs: Disallow loading ACPI tables when locked down", We verified the kernel source code 5.10.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=75b0cea7bf307f362057cc778efe89af4c615354

**Comment by amzdev0401** [comment] 2021-10-07 01:20
We have updated the needed changes, please review the updated files. Thank you.

**Comment by amzdev0401** [comment] 2021-10-30 13:13
I have noticed the same issue while testing in different operating systems and I have fixed the issue. I will update the modified files after testing is completed. 
Thank you for your quick response. We appreciate the attention you are giving to this review process.

**Comment by tSU-RooT** [comment] 2021-11-02 09:14
I am trying cross-review while refferring [reviewer-guidelines](https://github.com/rhboot/shim/wiki/reviewer-guidelines):
- Reproducibility is OK now.
```
Step 19/20 : RUN sha256sum shimx64.efi
 ---> Running in f93aa27d6b89
f8f35ad9fec3763b45eae7beaab74eb3d006f3eb94f7382dd1290dd488200980  shimx64.efi
```
Corresponding line in new build log is https://github.com/amzdev0401/shim-review/blob/a9bd5d4daa44d23f897dfeb739ac479cda5b5fce/build.log#L1438
- SBAT in shim binary looks good.
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.amzetta,1,SnapOS,shim,15.4,https://amzetta.com
```
- Organization(amzetta) looks match with cert(NOTE: self-signed certificate).
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            2a:30:c9:a9:9f:0a:3d:c0:70:03:ba:5a:c8:e6:77:58:3a:e4:13:4a
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = amzetta
        Validity
            Not Before: Feb 26 21:00:39 2021 GMT
            Not After : Feb 24 21:00:39 2031 GMT
        Subject: CN = amzetta
```
- Storing private key in hardware token(SafeNet eToken 5110) looks good.
- Vendor extension looks good(i.e. unique).
- Duration of cert is 10 years(embedded CA cert).
- According to the description, grub2 2.0.6(latest upstream release) is used.
- shim extra patches were all cherry-picked from upstream main branch.
These back port patches are already passed at Rocky Linux's submission(tagged as accepted), so I think these patches are OK.

Could someone(has authority to accept) review this submission?

**Comment by frozencemetery** [comment] 2021-11-24 15:35
- amzdev0401/shim-review is not a fork of this repo; please recreate it as one
- email verification could not be completed as PGP key fingerprints were not provided

**Comment by amzdev0401** [comment] 2021-11-26 20:00
Thank you for the update, I have updated the requested info, please let me know If I need to do anything in this SHIM submission.

1) amzdev0401/shim-review is not a fork of this repo; please recreate it as one
      In following branch we pull the SHIM source code 15.4 branch from https://github.com/rhboot/shim.git and build the SHIM binary. That information is available in the docker file.

https://github.com/amzdev0401/shim-review/blob/AmZettaTech-shim-X86_64-shim-15.4/Dockerfile
RUN  git clone --recursive -b 15.4 https://github.com/rhboot/shim.git shim


2) email verification could not be completed as PGP key fingerprints were not provided
loganathanr@amzetta.com
PGP Key ID: 2A2CF3A69E739955 PGP Key Fingerprint: 1920 A439 96A8 431B 6113 E95A 2A2C F3A6 9E73 9955, HKP key server: https://keyserver.ubuntu.com

Justinb@amzetta.com
PGP Key ID: 52D3D8F74C848F3A PGP Key Fingerprint: 87F2 B43A F046 F217 11CB 22AA 52D3 D8F7 4C84 8F3A, HKP key server: https://keyserver.ubuntu.com

**Comment by frozencemetery** [comment] 2021-11-29 20:57
>> amzdev0401/shim-review is not a fork of this repo; please recreate it as one
>
>  In following branch we pull the SHIM source code 15.4 branch directly from https://github.com/rhboot/shim.git and building the SHIM binary. That information is available in the following docker file.

While I can't speak for other reviewers, if you want a review from me, you need to adhere to the guidelines, which strongly suggest it to be an actual fork.

**Comment by amzdev0401** [comment] 2021-12-14 02:14
1. When I search by E-mail address in https://keyserver.ubuntu.com/  it provides the public key.

loganathanr@amzetta.com
https://keyserver.ubuntu.com/pks/lookup?search=loganathanr%40amzetta.com&fingerprint=on&op=index

Justinb@amzetta.com
https://keyserver.ubuntu.com/pks/lookup?search=justinb%40amzetta.com&fingerprint=on&op=index

2. @amzdev0401 
This git account is company account ( AmZetta Technologies,). Authorized users only can use. Now I am using for the SHIM submission.

**Comment by amzdev0401** [comment] 2021-12-14 16:51
About security contacts : Yes we will handle handle security updates, that is not a problem for us.

**Comment by amzdev0401** [comment] 2022-01-21 19:41
We are planning to add the secure boot feature in the upcoming product release, we are waiting for the SHIM approval. Can you please review the SHIM. Thank you.

**Comment by frozencemetery** [comment] 2022-02-04 00:03
I am going to send you some words.  When you receive them, please post them here.

**Comment by amzdev0401** [comment] 2022-02-04 01:16
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

spartanerer
vekstomr=C3=A5dets
utvis
godtgjorde
ferdigbehandlingens
Dardanellenes
held=C3=B8gnsomsorgens
omsetningsgjeldsbrevene
markmusas
varmfyllinger
encefalogrammer
testsalga
maratonforestillinga

**Comment by frozencemetery** [comment] 2022-02-04 14:47
You seem to have a problem handling utf-8 text, but that is otherwise correct.  Waiting on the other ones.

**Comment by amzdev0401** [comment] 2022-02-04 16:05
Thank you for the update. Do I need to do anything thing from my end ?. Please let me know.

**Comment by frozencemetery** [comment] 2022-02-04 16:22
You don't, but your other contact does - I emailed you both.

**Comment by amzdev0401** [comment] 2022-02-04 16:39
Hi, I have check my secondary contact, he said he didn't get any mail, he is waiting  for the mail to reply.
Could you please check.

Name: Justine Bagby 
- Position: Director - Sales 
- Email address: Justinb@amzetta.com
- PGP Key ID: 52D3D8F74C848F3A PGP Key Fingerprint: 87F2 B43A F046 F217 11CB 22AA 52D3 D8F7 4C84 8F3A, HKP key server: https://keyserver.ubuntu.com

**Comment by frozencemetery** [comment] 2022-02-04 16:49
Mail was sent to ***@***.*** from ***@***.*** on Thu, 03
Feb 2022 19:05:03 -0500 with subject "shim words" and encrypted body.
It was sent with Message-id of ***@***.*** .  Delivery
appears successful from my end - I have no indication otherwise.

Be well,
--Robbie

**Comment by amzdev0401** [comment] 2022-02-04 17:00
Thank you. Can you please resend the mail.

**Comment by frozencemetery** [comment] 2022-02-04 17:04
Resent.

**Comment by frozencemetery** [comment] 2022-02-04 17:41
Contact information is verified.  You might want to look into whatever's not processing utf-8 in your email stack properly, but that's not related to shim review :)

**Comment by amzdev0401** [comment] 2022-02-04 17:53
Thank you for the quick and prompt response. Greatly appreciated !!.

**Comment by ecos-platypus** [comment] 2022-03-10 09:22
I find it problematic that most of this submission is copy-pasted from #206 (as noted before by @julian-klode). If you diff the ISSUE_TEMPLATE.md (not filled out for AmZetta, you have to quote the first post in this issue and removed the leading quote markers) and README.md, most is exactly the same (e.g., `[keys are on HW eToken (SafeNet eToken 5110 FIPS) kept by authorized persons]`) or only with minimal changes. I simply cannot derive whether the vendor has taken time to familiarize with secure boot.

**Comment by amzdev0401** [comment] 2022-03-10 17:02
Yes we familiarized with secure boot. Regarding procedure for submission we had some issues but those were corrected based on the suggestions from the reviewer. Sorry for the issues earlier. Please let us know if anything needs to be updated for your review and we will take care of it immediately.

**Comment by amzdev0401** [comment] 2022-04-21 20:08
Could you please let us know anything do we need to do from our end.
We are waiting for this SHIM approval, we need to integrate this SHIM to our upcoming product release.

**Comment by amzdev0401** [comment] 2022-05-16 01:41
Could you please finish this review, we are waiting for the product release.

**Comment by julian-klode** [comment] 2022-06-14 09:57
Closing outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.

**Closed by julian-klode** 2022-06-14 09:57 UTC
Labels: new vendor
